/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AISettings {
  'salesforceApiKey' : string,
  'initialGreeting' : string,
  'botName' : string,
  'avatarImage' : [] | [ExternalBlob],
}
export interface Achievement {
  'id' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'featuredImage' : [] | [ExternalBlob],
  'publicationDate' : Time,
}
export interface CMSSettings {
  'theme' : string,
  'customSectionOrder' : Array<string>,
  'layoutOptions' : string,
}
export interface ContactForm {
  'id' : string,
  'salesforceId' : [] | [string],
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface ContentSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export interface DigitalMarketingData {
  'metricValue' : bigint,
  'timestamp' : Time,
  'metricName' : string,
}
export type ExternalBlob = Uint8Array;
export interface IntroductionSection {
  'id' : string,
  'bio' : string,
  'title' : string,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
}
export interface PublicAISettings {
  'initialGreeting' : string,
  'botName' : string,
  'avatarImage' : [] | [ExternalBlob],
}
export interface SiteStats {
  'totalBlogPosts' : bigint,
  'totalMessages' : bigint,
  'totalVisits' : bigint,
  'totalAchievements' : bigint,
}
export type Time = bigint;
export interface UISettings { 'theme' : string, 'layoutPreferences' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAchievement' : ActorMethod<[Achievement], undefined>,
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addContentSection' : ActorMethod<[ContentSection], undefined>,
  'addDigitalMarketingData' : ActorMethod<[DigitalMarketingData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAchievement' : ActorMethod<[string], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteContentSection' : ActorMethod<[string], undefined>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAiSettings' : ActorMethod<[], PublicAISettings>,
  'getAllDigitalMarketingData' : ActorMethod<[], Array<DigitalMarketingData>>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCmsSettings' : ActorMethod<[], CMSSettings>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getContentSections' : ActorMethod<[], Array<ContentSection>>,
  'getDigitalMarketingData' : ActorMethod<
    [string],
    [] | [DigitalMarketingData]
  >,
  'getFullAiSettings' : ActorMethod<[], AISettings>,
  'getIntroduction' : ActorMethod<[], IntroductionSection>,
  'getSiteStats' : ActorMethod<[], SiteStats>,
  'getUiSettings' : ActorMethod<[], UISettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContactForm' : ActorMethod<[ContactForm], undefined>,
  'updateAchievement' : ActorMethod<[Achievement], undefined>,
  'updateAiSettings' : ActorMethod<[AISettings], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateCmsSettings' : ActorMethod<[CMSSettings], undefined>,
  'updateContentSection' : ActorMethod<[ContentSection], undefined>,
  'updateDigitalMarketingData' : ActorMethod<[DigitalMarketingData], undefined>,
  'updateIntroduction' : ActorMethod<[IntroductionSection], undefined>,
  'updateSiteStats' : ActorMethod<[SiteStats], undefined>,
  'updateUiSettings' : ActorMethod<[UISettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];