/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Achievement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'featuredImage' : IDL.Opt(ExternalBlob),
  'publicationDate' : Time,
});
export const ContentSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const DigitalMarketingData = IDL.Record({
  'metricValue' : IDL.Nat,
  'timestamp' : Time,
  'metricName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublicAISettings = IDL.Record({
  'initialGreeting' : IDL.Text,
  'botName' : IDL.Text,
  'avatarImage' : IDL.Opt(ExternalBlob),
});
export const CMSSettings = IDL.Record({
  'theme' : IDL.Text,
  'customSectionOrder' : IDL.Vec(IDL.Text),
  'layoutOptions' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'id' : IDL.Text,
  'salesforceId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const AISettings = IDL.Record({
  'salesforceApiKey' : IDL.Text,
  'initialGreeting' : IDL.Text,
  'botName' : IDL.Text,
  'avatarImage' : IDL.Opt(ExternalBlob),
});
export const IntroductionSection = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
});
export const SiteStats = IDL.Record({
  'totalBlogPosts' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'totalVisits' : IDL.Nat,
  'totalAchievements' : IDL.Nat,
});
export const UISettings = IDL.Record({
  'theme' : IDL.Text,
  'layoutPreferences' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAchievement' : IDL.Func([Achievement], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addContentSection' : IDL.Func([ContentSection], [], []),
  'addDigitalMarketingData' : IDL.Func([DigitalMarketingData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAchievement' : IDL.Func([IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteContentSection' : IDL.Func([IDL.Text], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAiSettings' : IDL.Func([], [PublicAISettings], ['query']),
  'getAllDigitalMarketingData' : IDL.Func(
      [],
      [IDL.Vec(DigitalMarketingData)],
      ['query'],
    ),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCmsSettings' : IDL.Func([], [CMSSettings], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getContentSections' : IDL.Func([], [IDL.Vec(ContentSection)], ['query']),
  'getDigitalMarketingData' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DigitalMarketingData)],
      ['query'],
    ),
  'getFullAiSettings' : IDL.Func([], [AISettings], ['query']),
  'getIntroduction' : IDL.Func([], [IntroductionSection], ['query']),
  'getSiteStats' : IDL.Func([], [SiteStats], ['query']),
  'getUiSettings' : IDL.Func([], [UISettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContactForm' : IDL.Func([ContactForm], [], []),
  'updateAchievement' : IDL.Func([Achievement], [], []),
  'updateAiSettings' : IDL.Func([AISettings], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateCmsSettings' : IDL.Func([CMSSettings], [], []),
  'updateContentSection' : IDL.Func([ContentSection], [], []),
  'updateDigitalMarketingData' : IDL.Func([DigitalMarketingData], [], []),
  'updateIntroduction' : IDL.Func([IntroductionSection], [], []),
  'updateSiteStats' : IDL.Func([SiteStats], [], []),
  'updateUiSettings' : IDL.Func([UISettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Achievement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'featuredImage' : IDL.Opt(ExternalBlob),
    'publicationDate' : Time,
  });
  const ContentSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const DigitalMarketingData = IDL.Record({
    'metricValue' : IDL.Nat,
    'timestamp' : Time,
    'metricName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublicAISettings = IDL.Record({
    'initialGreeting' : IDL.Text,
    'botName' : IDL.Text,
    'avatarImage' : IDL.Opt(ExternalBlob),
  });
  const CMSSettings = IDL.Record({
    'theme' : IDL.Text,
    'customSectionOrder' : IDL.Vec(IDL.Text),
    'layoutOptions' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'id' : IDL.Text,
    'salesforceId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const AISettings = IDL.Record({
    'salesforceApiKey' : IDL.Text,
    'initialGreeting' : IDL.Text,
    'botName' : IDL.Text,
    'avatarImage' : IDL.Opt(ExternalBlob),
  });
  const IntroductionSection = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
  });
  const SiteStats = IDL.Record({
    'totalBlogPosts' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'totalVisits' : IDL.Nat,
    'totalAchievements' : IDL.Nat,
  });
  const UISettings = IDL.Record({
    'theme' : IDL.Text,
    'layoutPreferences' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAchievement' : IDL.Func([Achievement], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addContentSection' : IDL.Func([ContentSection], [], []),
    'addDigitalMarketingData' : IDL.Func([DigitalMarketingData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAchievement' : IDL.Func([IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteContentSection' : IDL.Func([IDL.Text], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAiSettings' : IDL.Func([], [PublicAISettings], ['query']),
    'getAllDigitalMarketingData' : IDL.Func(
        [],
        [IDL.Vec(DigitalMarketingData)],
        ['query'],
      ),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCmsSettings' : IDL.Func([], [CMSSettings], ['query']),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getContentSections' : IDL.Func([], [IDL.Vec(ContentSection)], ['query']),
    'getDigitalMarketingData' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DigitalMarketingData)],
        ['query'],
      ),
    'getFullAiSettings' : IDL.Func([], [AISettings], ['query']),
    'getIntroduction' : IDL.Func([], [IntroductionSection], ['query']),
    'getSiteStats' : IDL.Func([], [SiteStats], ['query']),
    'getUiSettings' : IDL.Func([], [UISettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContactForm' : IDL.Func([ContactForm], [], []),
    'updateAchievement' : IDL.Func([Achievement], [], []),
    'updateAiSettings' : IDL.Func([AISettings], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateCmsSettings' : IDL.Func([CMSSettings], [], []),
    'updateContentSection' : IDL.Func([ContentSection], [], []),
    'updateDigitalMarketingData' : IDL.Func([DigitalMarketingData], [], []),
    'updateIntroduction' : IDL.Func([IntroductionSection], [], []),
    'updateSiteStats' : IDL.Func([SiteStats], [], []),
    'updateUiSettings' : IDL.Func([UISettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };