/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SiteStats {
    totalBlogPosts: bigint;
    totalMessages: bigint;
    totalVisits: bigint;
    totalAchievements: bigint;
}
export interface PublicAISettings {
    initialGreeting: string;
    botName: string;
    avatarImage?: ExternalBlob;
}
export interface BlogPost {
    id: string;
    title: string;
    content: string;
    featuredImage?: ExternalBlob;
    publicationDate: Time;
}
export type Time = bigint;
export interface ContactForm {
    id: string;
    salesforceId?: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DigitalMarketingData {
    metricValue: bigint;
    timestamp: Time;
    metricName: string;
}
export interface IntroductionSection {
    id: string;
    bio: string;
    title: string;
    profileImage?: ExternalBlob;
    name: string;
}
export interface Achievement {
    id: string;
    title: string;
    date: Time;
    description: string;
    image?: ExternalBlob;
}
export interface UISettings {
    theme: string;
    layoutPreferences: string;
}
export interface AISettings {
    salesforceApiKey: string;
    initialGreeting: string;
    botName: string;
    avatarImage?: ExternalBlob;
}
export interface CMSSettings {
    theme: string;
    customSectionOrder: Array<string>;
    layoutOptions: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ContentSection {
    id: string;
    title: string;
    content: string;
    image?: ExternalBlob;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAchievement(newAchievement: Achievement): Promise<void>;
    addBlogPost(newPost: BlogPost): Promise<void>;
    addContentSection(newSection: ContentSection): Promise<void>;
    addDigitalMarketingData(newData: DigitalMarketingData): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAchievement(achievementId: string): Promise<void>;
    deleteBlogPost(postId: string): Promise<void>;
    deleteContentSection(sectionId: string): Promise<void>;
    getAchievements(): Promise<Array<Achievement>>;
    getAiSettings(): Promise<PublicAISettings>;
    getAllDigitalMarketingData(): Promise<Array<DigitalMarketingData>>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getCallerUserRole(): Promise<UserRole>;
    getCmsSettings(): Promise<CMSSettings>;
    getContactForms(): Promise<Array<ContactForm>>;
    getContentSections(): Promise<Array<ContentSection>>;
    getDigitalMarketingData(metricName: string): Promise<DigitalMarketingData | null>;
    getFullAiSettings(): Promise<AISettings>;
    getIntroduction(): Promise<IntroductionSection>;
    getSiteStats(): Promise<SiteStats>;
    getUiSettings(): Promise<UISettings>;
    isCallerAdmin(): Promise<boolean>;
    submitContactForm(form: ContactForm): Promise<void>;
    updateAchievement(updatedAchievement: Achievement): Promise<void>;
    updateAiSettings(newSettings: AISettings): Promise<void>;
    updateBlogPost(updatedPost: BlogPost): Promise<void>;
    updateCmsSettings(newSettings: CMSSettings): Promise<void>;
    updateContentSection(updatedSection: ContentSection): Promise<void>;
    updateDigitalMarketingData(updatedData: DigitalMarketingData): Promise<void>;
    updateIntroduction(newIntro: IntroductionSection): Promise<void>;
    updateSiteStats(newStats: SiteStats): Promise<void>;
    updateUiSettings(newSettings: UISettings): Promise<void>;
}
import type { AISettings as _AISettings, Achievement as _Achievement, BlogPost as _BlogPost, ContactForm as _ContactForm, ContentSection as _ContentSection, DigitalMarketingData as _DigitalMarketingData, ExternalBlob as _ExternalBlob, IntroductionSection as _IntroductionSection, PublicAISettings as _PublicAISettings, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAchievement(arg0: Achievement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(await to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(await to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addContentSection(arg0: ContentSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContentSection(await to_candid_ContentSection_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContentSection(await to_candid_ContentSection_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDigitalMarketingData(arg0: DigitalMarketingData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDigitalMarketingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDigitalMarketingData(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAchievement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAchievement(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteContentSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentSection(arg0);
            return result;
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAiSettings(): Promise<PublicAISettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiSettings();
                return from_candid_PublicAISettings_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiSettings();
            return from_candid_PublicAISettings_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDigitalMarketingData(): Promise<Array<DigitalMarketingData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDigitalMarketingData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDigitalMarketingData();
            return result;
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCmsSettings(): Promise<CMSSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getCmsSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCmsSettings();
            return result;
        }
    }
    async getContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactForms();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactForms();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentSections(): Promise<Array<ContentSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentSections();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentSections();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDigitalMarketingData(arg0: string): Promise<DigitalMarketingData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDigitalMarketingData(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDigitalMarketingData(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFullAiSettings(): Promise<AISettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullAiSettings();
                return from_candid_AISettings_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullAiSettings();
            return from_candid_AISettings_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntroduction(): Promise<IntroductionSection> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntroduction();
                return from_candid_IntroductionSection_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntroduction();
            return from_candid_IntroductionSection_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteStats(): Promise<SiteStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteStats();
            return result;
        }
    }
    async getUiSettings(): Promise<UISettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getUiSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUiSettings();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitContactForm(arg0: ContactForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(to_candid_ContactForm_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(to_candid_ContactForm_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAchievement(arg0: Achievement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAchievement(await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAchievement(await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAiSettings(arg0: AISettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAiSettings(await to_candid_AISettings_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAiSettings(await to_candid_AISettings_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(await to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(await to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCmsSettings(arg0: CMSSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCmsSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCmsSettings(arg0);
            return result;
        }
    }
    async updateContentSection(arg0: ContentSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentSection(await to_candid_ContentSection_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentSection(await to_candid_ContentSection_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDigitalMarketingData(arg0: DigitalMarketingData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDigitalMarketingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDigitalMarketingData(arg0);
            return result;
        }
    }
    async updateIntroduction(arg0: IntroductionSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIntroduction(await to_candid_IntroductionSection_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIntroduction(await to_candid_IntroductionSection_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSiteStats(arg0: SiteStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteStats(arg0);
            return result;
        }
    }
    async updateUiSettings(arg0: UISettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUiSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUiSettings(arg0);
            return result;
        }
    }
}
async function from_candid_AISettings_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AISettings): Promise<AISettings> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Achievement_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Promise<Achievement> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ContactForm_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactForm): ContactForm {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ContentSection_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentSection): Promise<ContentSection> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_IntroductionSection_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntroductionSection): Promise<IntroductionSection> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicAISettings_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicAISettings): Promise<PublicAISettings> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DigitalMarketingData]): DigitalMarketingData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    date: _Time;
    description: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: string;
    date: Time;
    description: string;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    initialGreeting: string;
    botName: string;
    avatarImage: [] | [_ExternalBlob];
}): Promise<{
    initialGreeting: string;
    botName: string;
    avatarImage?: ExternalBlob;
}> {
    return {
        initialGreeting: value.initialGreeting,
        botName: value.botName,
        avatarImage: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.avatarImage))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    featuredImage: [] | [_ExternalBlob];
    publicationDate: _Time;
}): Promise<{
    id: string;
    title: string;
    content: string;
    featuredImage?: ExternalBlob;
    publicationDate: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        featuredImage: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.featuredImage)),
        publicationDate: value.publicationDate
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    salesforceId: [] | [string];
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
}): {
    id: string;
    salesforceId?: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        salesforceId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.salesforceId)),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: string;
    content: string;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        image: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salesforceApiKey: string;
    initialGreeting: string;
    botName: string;
    avatarImage: [] | [_ExternalBlob];
}): Promise<{
    salesforceApiKey: string;
    initialGreeting: string;
    botName: string;
    avatarImage?: ExternalBlob;
}> {
    return {
        salesforceApiKey: value.salesforceApiKey,
        initialGreeting: value.initialGreeting,
        botName: value.botName,
        avatarImage: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.avatarImage))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    title: string;
    profileImage: [] | [_ExternalBlob];
    name: string;
}): Promise<{
    id: string;
    bio: string;
    title: string;
    profileImage?: ExternalBlob;
    name: string;
}> {
    return {
        id: value.id,
        bio: value.bio,
        title: value.title,
        profileImage: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Promise<Array<Achievement>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Achievement_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactForm>): Array<ContactForm> {
    return value.map((x)=>from_candid_ContactForm_n30(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentSection>): Promise<Array<ContentSection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ContentSection_n34(_uploadFile, _downloadFile, x)));
}
async function to_candid_AISettings_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AISettings): Promise<_AISettings> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function to_candid_Achievement_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Achievement): Promise<_Achievement> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_BlogPost_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPost): Promise<_BlogPost> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ContactForm_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactForm): _ContactForm {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function to_candid_ContentSection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentSection): Promise<_ContentSection> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_IntroductionSection_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntroductionSection): Promise<_IntroductionSection> {
    return await to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    featuredImage?: ExternalBlob;
    publicationDate: Time;
}): Promise<{
    id: string;
    title: string;
    content: string;
    featuredImage: [] | [_ExternalBlob];
    publicationDate: _Time;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        featuredImage: value.featuredImage ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.featuredImage)) : candid_none(),
        publicationDate: value.publicationDate
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    image?: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    content: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    salesforceId?: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}): {
    id: string;
    salesforceId: [] | [string];
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
} {
    return {
        id: value.id,
        salesforceId: value.salesforceId ? candid_some(value.salesforceId) : candid_none(),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salesforceApiKey: string;
    initialGreeting: string;
    botName: string;
    avatarImage?: ExternalBlob;
}): Promise<{
    salesforceApiKey: string;
    initialGreeting: string;
    botName: string;
    avatarImage: [] | [_ExternalBlob];
}> {
    return {
        salesforceApiKey: value.salesforceApiKey,
        initialGreeting: value.initialGreeting,
        botName: value.botName,
        avatarImage: value.avatarImage ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.avatarImage)) : candid_none()
    };
}
async function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    title: string;
    profileImage?: ExternalBlob;
    name: string;
}): Promise<{
    id: string;
    bio: string;
    title: string;
    profileImage: [] | [_ExternalBlob];
    name: string;
}> {
    return {
        id: value.id,
        bio: value.bio,
        title: value.title,
        profileImage: value.profileImage ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.profileImage)) : candid_none(),
        name: value.name
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    date: Time;
    description: string;
    image?: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    date: _Time;
    description: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
